package sk.kotlin.sensebox.bl.bt

enum class BleFailState {
    BT_NOT_ENABLED,
    SCAN_FINISHED,
    SCAN_ERROR,
    NOT_CONNECTED,
    CANNOT_CONNECT,
    CANNOT_WRITE_CHARACTERISTIC,
    CANNOT_WRITE_DESCRIPTOR,
    CANNOT_NOTIFY_CHARACTERISTIC,
    CANNOT_DISCOVER_SERVICES
}